### ISSUE TITLE
Add defaultTargetUrl to SAML application settings data model

### ISSUE THREAD

**Issue by kwevers** [patrickcping/pingone-go-sdk-v2#324]
The SAML application settings data model documentation has been extended with the `defaultTargetUrl` attribute. 

![Screenshot 2024-03-12 at 11 03 12](https://github.com/patrickcping/pingone-go-sdk-v2/assets/4541639/269cc51d-141f-444c-92a6-af88fef47bfc)

Reference: https://apidocs.pingidentity.com/pingone/platform/v1/api/#application-operations

According to support case 00819713 this attribute has been supported for a long time, but was never documented.
Can you add support to the SDK so that eventually the Terraform PingOne provider resource  `pingone_application` can be extended as well?

**Comment by kwevers** [comment]
I tried extending `management/generate/pingone-management.yml` myself, but I don't have any experience with go and a bunch of unrelated methods are being duplicated upon running `make generate`

**Comment by patrickcping** [comment]
Hi @kwevers !   Thanks for chasing down the undocumented attribute with us here.  The process to re-generate the client has manual steps to remove the duplicated methods in three files - they're not yet cleanly handled by the codegen process.  I can take it from here if you prefer, but in case you have the time the process would be:

1. Update the `management/generate/pingone-management.yml` OA3 spec
2. `cd ./management`
3. `make generate` (to generate just the `management` client code)
4. Discard the codegen's changes to `api_certificate_management.go`, `api_images.go` and `api_password_policies.go`

You should be left with just the changes to the SAML application model.

For the downstream Terraform provider, I've created issue https://github.com/pingidentity/terraform-provider-pingone/issues/761 and assigned it to the next release

**Comment by patrickcping** [comment]
Merged to main
